name: Prettier

on:
  pull_request:
  workflow_dispatch:

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Prettier Check
        run: npx prettier . --check
